package InterfazGrafica;
/*
*  Pablo Valenzuela Álvarez
*  Francisco Javier García Maldonado
*  
*  Recuperación de Información
*  2017/2018
*  Practica 5
*/

import Buscador.Buscador;
import java.io.IOException;
import java.nio.file.Paths;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.apache.lucene.facet.taxonomy.directory.DirectoryTaxonomyReader;
import org.apache.lucene.index.DirectoryReader;
import org.apache.lucene.queryparser.classic.ParseException;
import org.apache.lucene.search.IndexSearcher;
import org.apache.lucene.search.TopDocs;
import org.apache.lucene.store.Directory;
import org.apache.lucene.store.FSDirectory;
/*import static Buscador.Buscador.busqueda;
import static Buscador.Buscador.hacerDrillDown;
import static Buscador.Buscador.muestraFacetas;
import static Buscador.Buscador.muestraResults;*/
import java.awt.event.InputMethodListener;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreeModel;
import javax.swing.tree.TreeNode;
import org.apache.lucene.document.Document;
import org.apache.lucene.facet.FacetResult;
import org.apache.lucene.facet.Facets;
import org.apache.lucene.facet.LabelAndValue;
import org.apache.lucene.facet.taxonomy.FastTaxonomyFacetCounts;
import org.apache.lucene.search.ScoreDoc;

/**
 *
 * @author Franelas
 */


public class InterfazGrafica extends javax.swing.JFrame {
    //Variables de clase
    /*private TopDocs resultados_busqueda;
    private IndexSearcher searcher;
    private DirectoryReader reader;
    private DirectoryTaxonomyReader taxoReader;*/
    Buscador buscador;
    TopDocs res;
    
    //Constructor de clase
    public InterfazGrafica(String index, String facet) throws IOException {
        initComponents();
        JTA_Resultados.setEditable(false);
        buscador = new Buscador();
        buscador.inicializar(index, facet);
        //Inicializamos las variables para poder leer los datos de los índices
        /*Directory indexDir = FSDirectory.open(Paths.get(index));
        reader = DirectoryReader.open(indexDir);
        searcher = new IndexSearcher(reader);*/
        
        //Inicializamos las variables para poder leer los datos de las facetas
       /* Directory taxoDir = FSDirectory.open(Paths.get(facet));
        taxoReader = new DirectoryTaxonomyReader(taxoDir);*/

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        JT_Facetas = new javax.swing.JTree();
        jScrollPane4 = new javax.swing.JScrollPane();
        JTP_Cuadrobusqueda = new javax.swing.JTextPane();
        JL_Titulo = new javax.swing.JLabel();
        JCB_Indices = new javax.swing.JComboBox<>();
        JL_Subtitulo = new javax.swing.JLabel();
        JB_Buscar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        JTA_Resultados = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));

        jScrollPane1.setViewportView(JT_Facetas);

        JTP_Cuadrobusqueda.setToolTipText("");
        JTP_Cuadrobusqueda.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                JTP_CuadrobusquedaInputMethodTextChanged(evt);
            }
        });
        jScrollPane4.setViewportView(JTP_Cuadrobusqueda);

        JL_Titulo.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        JL_Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JL_Titulo.setText("Recuperación de Información sobre SCOPUS");

        JCB_Indices.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Title", "Abstract", "Author Keywords", "Index Keywords" }));
        JCB_Indices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCB_IndicesActionPerformed(evt);
            }
        });

        JL_Subtitulo.setText("BÚSQUEDA");

        JB_Buscar.setText("Buscar");
        JB_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_BuscarActionPerformed(evt);
            }
        });

        JTA_Resultados.setColumns(20);
        JTA_Resultados.setRows(5);
        jScrollPane2.setViewportView(JTA_Resultados);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(222, 222, 222)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(JL_Subtitulo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JL_Titulo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
                            .addComponent(jScrollPane4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JB_Buscar, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                        .addGap(125, 125, 125))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JCB_Indices, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(JL_Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addGap(30, 30, 30)
                .addComponent(JL_Subtitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JB_Buscar, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                    .addComponent(jScrollPane4))
                .addGap(13, 13, 13)
                .addComponent(JCB_Indices, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 15, Short.MAX_VALUE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    /**************************************************************************\
    |                    DESPLEGABLE SELECCIÓN DE INDICE                       |
    \**************************************************************************/
    private void JCB_IndicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCB_IndicesActionPerformed
        
    }//GEN-LAST:event_JCB_IndicesActionPerformed
    
    
    /**************************************************************************\
    |                           BOTON DE BÚSQUEDA                              |
    \**************************************************************************/
    private void JB_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_BuscarActionPerformed
        //OBTENEMOS DATOS PARA BÚSQUEDA
        int i = JCB_Indices.getSelectedIndex();
        String indice = JCB_Indices.getItemAt(i);
        String cadena_busqueda = JTP_Cuadrobusqueda.getText();        
        //trim(): borra espacios en blanco delante y detrás de la cadena de texto
        cadena_busqueda = cadena_busqueda.trim();
        //Cantidad de documentos que devuelve la función tras realizar una búsqueda
        int cantidad_docs = 20;
        
        //REALIZAMOS LA BÚSQUEDA
        try {
            //public static TopDocs busqueda(String field, String query, int tam)
            res = buscador.busqueda(indice, cadena_busqueda, cantidad_docs);
            ActualizaPantalla(res);
        } catch (ParseException | IOException ex) {
            Logger.getLogger(InterfazGrafica.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        JOptionPane.showMessageDialog(this, indice+", "+cadena_busqueda+", la busqueda se ha realizado correctamente");
        
        //MOSTRAMOS POR PANTALLA LOS RESULTADOS en JList1_ResltsValueChanged
        
    }//GEN-LAST:event_JB_BuscarActionPerformed

    private void ActualizaPantalla(TopDocs top) throws IOException   {
        //System.out.println("Resultados:");
        JTA_Resultados.setText("");
        JTA_Resultados.setText("Resultados\n");
        //JLi_Resultados.add
        
        for (ScoreDoc mec : top.scoreDocs) {
            Document d = buscador.getSearcher().doc(mec.doc);
            JTA_Resultados.append(mec.score+" "+d.get("Title")+"\n");
        }
        
        /*DefaultMutableTreeNode topa = new DefaultMutableTreeNode("The Java Series");
        DefaultMutableTreeNode category = null;
        DefaultMutableTreeNode book = null;
        
        category = new DefaultMutableTreeNode("Books for Java Programmers");
        topa.add(category);
    
            //original Tutorial
        book = new DefaultMutableTreeNode("The Java Tutorial: A Short Course on the Basics");
        category.add(book);
    
        //Tutorial Continued
        book = new DefaultMutableTreeNode("The Java Tutorial Continued: The Rest of the JDK");
        category.add(book);

        //Swing Tutorial
        book = new DefaultMutableTreeNode("The Swing Tutorial: A Guide to Constructing GUIs");
        category.add(book);
        
        TreeModel tm = new DefaultTreeModel(topa);       
        
        JT_Facetas.setModel(tm);*/
                
        Facets fCounts = new FastTaxonomyFacetCounts(buscador.getTaxonomyReader(), buscador.getFacetsConfig(), buscador.getFacetsCollector());                
        List<FacetResult> allDims = fCounts.getAllDims(10); 
        
        DefaultMutableTreeNode topa = new DefaultMutableTreeNode("grande pene");
        DefaultMutableTreeNode category = null;
        DefaultMutableTreeNode book = null;
        /*System.out.println("Total hits: "+top.totalHits);
        System.out.println("Categorias "+allDims.size());*/
        
        for(FacetResult fr: allDims){
            //System.out.println("Dimension: "+fr.dim);
            category = new DefaultMutableTreeNode("Dimensión: "+fr.dim);
            topa.add(category);
            for(LabelAndValue lav: fr.labelValues){
                //System.out.println("    "+lav.label+":: -> "+lav.value);
                book = new DefaultMutableTreeNode(lav.label);
                category.add(book);
            }
        }
        TreeModel tm = new DefaultTreeModel(topa);    
        JT_Facetas.setModel(tm);
    }
    
    private void JTP_CuadrobusquedaInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_JTP_CuadrobusquedaInputMethodTextChanged
        
    }//GEN-LAST:event_JTP_CuadrobusquedaInputMethodTextChanged

    
    /**************************************************************************\
    |                                  MAIN                                    |
    | @param args                                                              |
    \**************************************************************************/
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                String INDEX_DIR = "../resultados/index";
                String FACET_DIR = "../resultados/facet";
                try {
                    new InterfazGrafica(INDEX_DIR, FACET_DIR).setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(InterfazGrafica.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB_Buscar;
    private javax.swing.JComboBox<String> JCB_Indices;
    private javax.swing.JLabel JL_Subtitulo;
    private javax.swing.JLabel JL_Titulo;
    private javax.swing.JTextArea JTA_Resultados;
    private javax.swing.JTextPane JTP_Cuadrobusqueda;
    private javax.swing.JTree JT_Facetas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
