package InterfazGrafica;
/*
*  Pablo Valenzuela Álvarez
*  Francisco Javier García Maldonado
*  
*  Recuperación de Información
*  2017/2018
*  Practica 5
*/

import java.io.IOException;
import java.nio.file.Paths;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.apache.lucene.facet.taxonomy.directory.DirectoryTaxonomyReader;
import org.apache.lucene.index.DirectoryReader;
import org.apache.lucene.queryparser.classic.ParseException;
import org.apache.lucene.search.IndexSearcher;
import org.apache.lucene.search.TopDocs;
import org.apache.lucene.store.Directory;
import org.apache.lucene.store.FSDirectory;
import static Buscador.Buscador.busqueda;
import static Buscador.Buscador.hacerDrillDown;
import static Buscador.Buscador.muestraFacetas;
import static Buscador.Buscador.muestraResults;
import java.awt.event.InputMethodListener;
import javax.swing.JOptionPane;

/**
 *
 * @author Franelas
 */


public class InterfazGrafica extends javax.swing.JFrame {
    //Variables de clase
    private TopDocs resultados_busqueda;
    private IndexSearcher searcher;
    private DirectoryReader reader;
    private DirectoryTaxonomyReader taxoReader;
    
    //Constructor de clase
    public InterfazGrafica(String index, String facet) throws IOException {
        initComponents();
        //Inicializamos las variables para poder leer los datos de los índices
        Directory indexDir = FSDirectory.open(Paths.get(index));
        reader = DirectoryReader.open(indexDir);
        searcher = new IndexSearcher(reader);
        
        //Inicializamos las variables para poder leer los datos de las facetas
        Directory taxoDir = FSDirectory.open(Paths.get(facet));
        taxoReader = new DirectoryTaxonomyReader(taxoDir);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        JT_Facetas = new javax.swing.JTree();
        jScrollPane4 = new javax.swing.JScrollPane();
        JTP_Cuadrobusqueda = new javax.swing.JTextPane();
        JL_Titulo = new javax.swing.JLabel();
        JCB_Indices = new javax.swing.JComboBox<>();
        JL_Subtitulo = new javax.swing.JLabel();
        JB_Buscar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        JLi_Resultados = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));

        jScrollPane1.setViewportView(JT_Facetas);

        JTP_Cuadrobusqueda.setToolTipText("");
        JTP_Cuadrobusqueda.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                JTP_CuadrobusquedaInputMethodTextChanged(evt);
            }
        });
        jScrollPane4.setViewportView(JTP_Cuadrobusqueda);

        JL_Titulo.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        JL_Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JL_Titulo.setText("Recuperación de Información sobre SCOPUS");

        JCB_Indices.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Title", "Abstract", "Author Keywords", "Index Keywords" }));
        JCB_Indices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCB_IndicesActionPerformed(evt);
            }
        });

        JL_Subtitulo.setText("BÚSQUEDA");

        JB_Buscar.setText("Buscar");
        JB_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_BuscarActionPerformed(evt);
            }
        });

        JLi_Resultados.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        JLi_Resultados.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                JLi_ResultadosValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(JLi_Resultados);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3)
                .addGap(123, 123, 123))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(222, 222, 222)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(JL_Subtitulo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JL_Titulo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
                            .addComponent(jScrollPane4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JB_Buscar, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                        .addGap(125, 125, 125))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JCB_Indices, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(JL_Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addGap(30, 30, 30)
                .addComponent(JL_Subtitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JB_Buscar, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                    .addComponent(jScrollPane4))
                .addGap(13, 13, 13)
                .addComponent(JCB_Indices, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 15, Short.MAX_VALUE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    /**************************************************************************\
    |                    DESPLEGABLE SELECCIÓN DE INDICE                       |
    \**************************************************************************/
    private void JCB_IndicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCB_IndicesActionPerformed
        
    }//GEN-LAST:event_JCB_IndicesActionPerformed
    
    
    /**************************************************************************\
    |                           BOTON DE BÚSQUEDA                              |
    \**************************************************************************/
    private void JB_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_BuscarActionPerformed
        //OBTENEMOS DATOS PARA BÚSQUEDA
        String indice = JCB_Indices.getPrototypeDisplayValue();
        String cadena_busqueda = JTP_Cuadrobusqueda.getContentType();
        //trim(): borra espacios en blanco delante y detrás de la cadena de texto
        cadena_busqueda = cadena_busqueda.trim();
        //Cantidad de documentos que devuelve la función tras realizar una búsqueda
        int cantidad_docs = 20;
        
        //REALIZAMOS LA BÚSQUEDA
        try {
            //public static TopDocs busqueda(String field, String query, int tam)
            resultados_busqueda = busqueda(indice, cadena_busqueda, cantidad_docs);
        } catch (ParseException | IOException ex) {
            Logger.getLogger(InterfazGrafica.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        JOptionPane.showMessageDialog(this, indice+", "+cadena_busqueda+", la busqueda se ha realizado correctamente");
        
        //MOSTRAMOS POR PANTALLA LOS RESULTADOS en JList1_ResltsValueChanged
        
    }//GEN-LAST:event_JB_BuscarActionPerformed

    private void JLi_ResultadosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_JLi_ResultadosValueChanged
        //MOSTRAMOS EL ARRAY CON CADA RESULTADO
        //public static void muestraResults(TopDocs top) throws IOException
        
        System.out.println("Resultados obtenidos para la búsqueda realizada:");
        
        try {
            muestraResults(resultados_busqueda);
        } catch (IOException ex) {
            Logger.getLogger(InterfazGrafica.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_JLi_ResultadosValueChanged

    private void JTP_CuadrobusquedaInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_JTP_CuadrobusquedaInputMethodTextChanged
        
    }//GEN-LAST:event_JTP_CuadrobusquedaInputMethodTextChanged

    
    /**************************************************************************\
    |                                  MAIN                                    |
    | @param args                                                              |
    \**************************************************************************/
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                String INDEX_DIR = "../resultados/index";
                String FACET_DIR = "../resultados/facet";
                
                try {
                    new InterfazGrafica(INDEX_DIR, FACET_DIR).setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(InterfazGrafica.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB_Buscar;
    private javax.swing.JComboBox<String> JCB_Indices;
    private javax.swing.JLabel JL_Subtitulo;
    private javax.swing.JLabel JL_Titulo;
    private javax.swing.JList<String> JLi_Resultados;
    private javax.swing.JTextPane JTP_Cuadrobusqueda;
    private javax.swing.JTree JT_Facetas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
